name: Deploy Godot Web

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: barichello/godot-ci:4.6.3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        run: |
          mkdir -p ~/.config
          ln -s /root/.local ~/.local
          ln -s /root/.config/godot ~/.config/godot

      - name: Verify templates
        run: |
          echo "HOME=$HOME"
          find / -iname "web_nothreads*" 2>/dev/null
          find / -iname "web_*.zip" 2>/dev/null

      - name: Cache bust Godot assets
        run: |
          VERSION=${{ github.sha }}

          sed -i "s|\.wasm|.wasm?v=$VERSION|g" build/index.html
          sed -i "s|\.pck|.pck?v=$VERSION|g" build/index.html
          sed -i "s|\.js|.js?v=$VERSION|g" build/index.html
          
      - name: Export Web
        run: |
          mkdir -p build
          godot --headless --export-release "Web" build/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    runs-on: ubuntu-24.04
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4